CREATE TABLE IF NOT EXISTS `#__wichlacz` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `state` tinyint(1) NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `range_heating_min` float NOT NULL,
  `range_heating_max` float NOT NULL,
  `price` int(11) NOT NULL,
  `power` float NOT NULL,
  `max_working_pressure` float NOT NULL,
  `width_furnace_door` int(11) NOT NULL,
  `height_furnace_door` int(11) NOT NULL,
  `height_furnace` int(11) NOT NULL,
  `length_furnace` int(11) NOT NULL,
  `width_furnace` int(11) NOT NULL,
  `depth_furnace` int(11) NOT NULL,
  `volume_furnace` int(11) NOT NULL,
  `volume_water` int(11) NOT NULL,
  `height_d_t_min` int(11) NOT NULL,
  `cross_section_chimney` int(11) NOT NULL,
  `thickness_metal_furnace` int(11) NOT NULL,
  `connection` text NOT NULL,
  `article_id` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=62 ;